---
# This playbook contains common plays that will be run on all nodes.

- name: update apt packages
  apt: update_cache=yes cache_valid_time=3600

- name: install supporting packages to manage apt repositories
  apt: pkg={{ item }} state=latest
  with_items:
    - software-properties-common
    - python-software-properties
    - python
    - g++
    - make

- name: add 3rd party apt repositories
  apt_repository: repo='{{ item }}' state=present
  with_items:
    - ppa:chris-lea/node.js

- name: installing tools and utility packages
  apt: pkg={{ item }} state=latest
  with_items:
    - wget
    - curl
    - htop
    - unzip
    - git
    - python-pip
    - nodejs

- name: fix issue with NodeJS and self-signed certificates
  command: npm config set ca ""

- name: install nodejs modules
  npm: name={{ item }} state=present global=yes
  with_items:
    - less

- name: install python libraries
  pip: name={{ item }}
  with_items:
    - passlib
    - yolk

- name: update /etc/hosts (on vagrant box)
  lineinfile: dest=/etc/hosts regexp='.*{{ item.hostname }}$' line='{{ item.ip }} {{ item.hostname }}' state=present
  with_items:
    - {hostname: "dbserver", ip: "{{ development_db_server }}"}
  when: is_vagrant is defined

- name: update /etc/hosts (on production)
  lineinfile: dest=/etc/hosts regexp='.*{{ item.hostname }}$' line='{{ item.ip }} {{ item.hostname }}' state=present
  with_items:
    - {hostname: "dbserver", ip: "{{ production_db_server }}"}
  when: is_vagrant is not defined
